<?php

return [
    'models' => [
        'user' => \Bonlineza\DearDatabase\Models\User::class,
        'supplier' => \Bonlineza\DearDatabase\Models\Supplier::class,
        'customer' => \Bonlineza\DearDatabase\Models\Customer::class,
        'contact' => \Bonlineza\DearDatabase\Models\Contact::class,
        'contact_address' => \Bonlineza\DearDatabase\Models\ContactAddress::class,
        'purchase' => \Bonlineza\DearDatabase\Models\Purchase::class,
        'purchase_order' => \Bonlineza\DearDatabase\Models\PurchaseOrder::class,
        'purchase_stock' => \Bonlineza\DearDatabase\Models\PurchaseStock::class,
        'purchase_invoice' => \Bonlineza\DearDatabase\Models\PurchaseInvoice::class,
        'purchase_credit_note' => \Bonlineza\DearDatabase\Models\PurchaseCreditNote::class,
        'purchase_manual_journal' => \Bonlineza\DearDatabase\Models\PurchaseManualJournal::class,
        'additional_attribute' => \Bonlineza\DearDatabase\Models\AdditionalAttribute::class,
        'attachment_line' => \Bonlineza\DearDatabase\Models\AttachmentLine::class,
        'inventory_movement_line' => \Bonlineza\DearDatabase\Models\InventoryMovementLine::class,
        'address' => \Bonlineza\DearDatabase\Models\Address::class,
        'purchase_shipping_address' => \Bonlineza\DearDatabase\Models\PurchaseShippingAddress::class,
        'purchase_order_line' => \Bonlineza\DearDatabase\Models\PurchaseOrderLine::class,
        'purchase_invoice_line' => \Bonlineza\DearDatabase\Models\PurchaseInvoiceLine::class,
        'purchase_payment_line' => \Bonlineza\DearDatabase\Models\PurchasePaymentLine::class,
        'purchase_additional_charge' => \Bonlineza\DearDatabase\Models\PurchaseAdditionalCharge::class,
        'purchase_invoice_additional_charge' => \Bonlineza\DearDatabase\Models\PurchaseInvoiceAdditionalCharge::class,
        'purchase_stock_line' => \Bonlineza\DearDatabase\Models\PurchaseStockLine::class,
        'purchase_unstock_line' => \Bonlineza\DearDatabase\Models\PurchaseUnstockLine::class,
        'purchase_manual_journal_line' => \Bonlineza\DearDatabase\Models\PurchaseManualJournalLine::class,
        'sale' => \Bonlineza\DearDatabase\Models\Sale::class,
        'sale_quote' => \Bonlineza\DearDatabase\Models\SaleQuote::class,
        'sale_order' => \Bonlineza\DearDatabase\Models\SaleOrder::class,
        'sale_shipping_address' => \Bonlineza\DearDatabase\Models\SaleShippingAddress::class,
        'sale_manual_journal' => \Bonlineza\DearDatabase\Models\SaleManualJournal::class,
        'sale_credit_note' => \Bonlineza\DearDatabase\Models\SaleCreditNote::class,
        'sale_invoice' => \Bonlineza\DearDatabase\Models\SaleInvoice::class,
        'sale_fulfilment' => \Bonlineza\DearDatabase\Models\SaleFulfilment::class,
        'sale_payment_line' => \Bonlineza\DearDatabase\Models\SalePaymentLine::class,
        'sale_quote_line' => \Bonlineza\DearDatabase\Models\SaleQuoteLine::class,
        'sale_additional_charge' => \Bonlineza\DearDatabase\Models\SaleAdditionalCharge::class,
        'sale_order_line' => \Bonlineza\DearDatabase\Models\SaleOrderLine::class,
        'sale_manual_journal_line' => \Bonlineza\DearDatabase\Models\SaleManualJournalLine::class,
        'sale_fulfilment_pick' => \Bonlineza\DearDatabase\Models\SaleFulfilmentPick::class,
        'sale_fulfilment_pack' => \Bonlineza\DearDatabase\Models\SaleFulfilmentPack::class,
        'sale_fulfilment_ship' => \Bonlineza\DearDatabase\Models\SaleFulfilmentShip::class,
        'sale_fulfilment_pick_line' => \Bonlineza\DearDatabase\Models\SaleFulfilmentPickLine::class,
        'sale_fulfilment_pack_line' => \Bonlineza\DearDatabase\Models\SaleFulfilmentPackLine::class,
        'sale_fulfilment_ship_line' => \Bonlineza\DearDatabase\Models\SaleFulfilmentShipLine::class,
        'sale_invoice_line' => \Bonlineza\DearDatabase\Models\SaleInvoiceLine::class,
        'sale_invoice_additional_charge' => \Bonlineza\DearDatabase\Models\SaleInvoiceAdditionalCharge::class,
        'sale_restock_line' => \Bonlineza\DearDatabase\Models\SaleRestockLine::class,
    ]
];
