name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:11.3
        env:
          POSTGRES_PASSWORD: pass123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Setup PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install php dependencies
        uses: "ramsey/composer-install@v2"

      - name: Larastan
        run: composer analyse

      - name: PHP Unit
        run: composer test
